### ISSUE TITLE
Cannot retrieve Custom Vision SDK from NuGet to build sample

### ISSUE THREAD

**Issue by jensemil** [microsoft/Cognitive-CustomVision-Windows#1]
Hi,
I believe the sample generally does not build at the moment, because the Microsoft.Cognitive.CustomVision.Prediction and Microsoft.Cognitive.CustomVision.Training do not install when I try to click restore from NuGet.

I tried on two different machines, a Windows PC and a Windows Server - both with the newest version of Microsoft Visual Studio 2017 - yielding two different errors it seems, however, causing the same problem.

Windows PC:
![sample-error-pc](https://cloud.githubusercontent.com/assets/6105088/26152688/e4a3c55c-3aff-11e7-94d8-d09d137e3f54.PNG)

Windows Server:
![sample-error-windows-server](https://cloud.githubusercontent.com/assets/6105088/26152744/27824bc8-3b00-11e7-85eb-fc947c2fb766.PNG)

Regards, Jens Emil

**Comment by pj-ms** [comment]
Hi,

It should be a problem of the source of sdk. I submitted a pull request, which should solve this problem: https://github.com/Microsoft/Cognitive-CustomVision-Windows/pull/3 .

You can try if this change helps.

Thanks

Ping

**Comment by chsienki** [comment]
Fixed with #3
