### ISSUE TITLE
API updated but sample not

### ISSUE THREAD

**Issue by mydreamworldpolly** [microsoft/Cognitive-CustomVision-Windows#12]
I  have tested CustomVision.Sample and it works well. But when I create a new project and download packages(Microsoft.Cognitive.CustomVision.Prediction,Microsoft.Cognitive.CustomVision.Training)from nuget，there's something wrong in the sample program:  

            TrainingApiCredentials trainingCredentials = new TrainingApiCredentials(trainingKey);
            TrainingApi trainingApi = new TrainingApi(trainingCredentials);

            PredictionEndpointCredentials predictionEndpointCredentials = new 
           PredictionEndpointCredentials(predictionKey);
            PredictionEndpoint endpoint = new PredictionEndpoint(predictionEndpointCredentials);
the right way may be this:
            TrainingApi trainingApi = new TrainingApi() { ApiKey = trainingKey };
          PredictionEndpoint endpoint = new PredictionEndpoint() { ApiKey = predictionKey };

reference: 
https://docs.microsoft.com/fi-fi/azure/cognitive-services/custom-vision-service/csharp-tutorial

**Comment by cthrash** [comment]
The code in this repo has been [updated](https://github.com/Microsoft/Cognitive-CustomVision-Windows/pull/11).  It should now match the NuGet and the tutorial.  Please confirm.

**Comment by mydreamworldpolly** [comment]
Thanks for the fix.  @cthrash
