### ISSUE TITLE
TrainingApi.CreateImagesFromFilesAsync with folder containing more than 55Mb of images throws RequestTimeout

### ISSUE THREAD

**Issue by daltskin** [microsoft/Cognitive-CustomVision-Windows#13]
Getting RequestTimeout error thrown when calling TrainingApi.CreateImagesFromFilesAsync - when using folders with large image repositories.  Below currentFolder contains 50 images, totalling approx. 60mb.  The below code will throw RequestTimeout

```
var images = Directory.GetFiles(currentFolder).ToList();
var imageFiles = images.Select(img => new ImageFileCreateEntry(Path.GetFileName(img), File.ReadAllBytes(img))).ToList();
var imageBatch = new ImageFileCreateBatch(imageFiles);
var summary = await trainingApi.CreateImagesFromFilesAsync(project.Id, new ImageFileCreateBatch(imageFiles));
```
Error: RequestTimeout

{Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'RequestTimeout'
   at Microsoft.Cognitive.CustomVision.Training.TrainingApi.<CreateImagesFromFilesWithHttpMessagesAsync>d__29.MoveNext()

However, deleting some files to get the total below 55Mb works.

**Comment by shonohs** [comment]
This repository is deprecated
