### ISSUE TITLE
Getting "Operation returned an invalid status code 'Unauthorized'" when creating a custom vision project for which I have a valid training key

### ISSUE THREAD

**Issue by shmisra** [microsoft/Cognitive-CustomVision-Windows#16]
Getting Operation returned an invalid status code 'Unauthorized' when creating a custom vision project for which I have a valid training key.

 static void Main(string[] args)
        {
            // https://customvision.ai/projects#/settings
            // Add your training key from the settings page of the portal

            string trainingKey = "<redacted>";

            // Create the Api, passing in the training key
            TrainingApi trainingApi = new TrainingApi() { ApiKey = trainingKey };

            // Create a new project

            Console.WriteLine("Creating new project:");

            var project = trainingApi.CreateProject("My New Project");<== This returns Operation returned an invalid status code 'Unauthorized'
<SNIP>

**Comment by chsienki** [comment]
Edited comment to remove training key. 

Please don't paste keys in public! They're secrets and should be treated much like a password, as anyone with it can gain access to your account.

**Comment by DaveVoyles** [comment]
I'm running into the same issue with the python API. 

Worked fine the first time I tried to do this. And then any new call to the API afterwards results in:

HttpOperationError: Operation returned an invalid status code 'Bad Request'

**Comment by areddish** [comment]
@DaveVoyles  'Bad Request' can get sent back if you have exceeded the project limit for your account.

You can check this limit by logging into http://customvision.ai and clicking on the Gear icon in the upper right. You should see your keys and below a list of how many projects you have created and how many more you can create.

**Comment by DaveVoyles** [comment]
@areddish I thought that may be it as well, but I am currently at *21 predictions made; 9979 remain until reset*

I'm going to keep sifting through this and see what I can come up with. I may just make a new project and see how it goes.

**Comment by areddish** [comment]
@DaveVoyles  Are you having issues with create project or predict image?

If it's predict image then there are a few things to check:

1. That you have a trained iteration
2. If you aren't passing an iteration id to the prediction call then you need to have one of the trained iterations in the project marked as default (you can check this on the project's performance tab)

**Comment by DaveVoyles** [comment]
I just figured out what it was. You cannot have more than 2 projects are any given time. 

Once I deleted a project, I could then create a new one. I tried this by making a request with HTTP, but also when I used the VoTT tool to upload my images directly to the Custom Vision service.

**Comment by vayinapurapu** [comment]
@Dave, I am facing the same challenge. Can you please let me know, how did you delete the project?

**Comment by areddish** [comment]
@vayin you can delete a project from the portal (https://customvision.ai) or via the SDK you can GetProjects() and then call DeleteProject on one or more of the projects you wish to delete.

**Comment by SQLScott** [comment]
So, i'm getting this Bad Request error with Python. I am opening an existing project:
project = trainer.get_project("_project_id_")
but when I hit the train_project line, I get the Bad Request error.
iteration = trainer.train_project(project.id)

I only have 1 project, and I have the appropriate number of images and tags. So, i'm not sure why I am getting this error.

**Comment by mkalicharan** [comment]
Same problem for me..i have no existing projects but it still gives the same error Operation returned an invalid status code 'Bad Request'

**Comment by liangcht** [comment]
@mkalicharan do you mean you don't have any existing project but getting Bad Request when you try to create a project?

**Comment by mkalicharan** [comment]
Yes, the first project that i am creating on my profile, gets that error

**Comment by liangcht** [comment]
@mkalicharan are you able to create one from custom vision portal (https://customvision.ai) ?

**Comment by liangcht** [comment]
@mkalicharan can you try catch the exception 
try: 
    [things you want to do]
except Exception e:
    print e.response.content

And see what that tells you?

**Comment by mperejda** [comment]
if you go to https://www.customvision.ai/projects#/settings and notice your endpoint url looks like the following

https://southcentralus.api.cognitive.microsoft.com/customvision/...

you may need to change to Location of your resource group in azure to South Central US

**Comment by riyaz4s** [comment]
Still getting the `Unauthorized` error

`Unhandled Exception: Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'Unauthorized'
   at Microsoft.Azure.CognitiveServices.Vision.CustomVision.Training.TrainingApi.GetProjectsWithHttpMessagesAsync(Dictionary 2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.CognitiveServices.Vision.CustomVision.Training.TrainingApiExtensions.GetProjectsAsync(ITrainingApi operations, CancellationToken cancellationToken)
   at Microsoft.Azure.CognitiveServices.Vision.CustomVision.Training.TrainingApiExtensions.GetProjects(ITrainingApi operations)
   at Import.Program.Main(String[] args) in /Users/riyaz/Playground/AISchoolTutorials/sketch2code/Import/Program.cs:line 29`

**Comment by vibhu30080** [comment]
I am having the same issue while uploading json file for trained images can anybody help here??

**Comment by aljaiban** [comment]
Same here. Getting Unauthorized though everything should be fine. I am using .NET SDK.

**Comment by aljaiban** [comment]
My bad. I found out that I was using Custom Vision Azure Service but using using Microsoft.Azure.CognitiveServices.Vision.ComputerVision nuget package with it. I really wanted to use Computer Vision Azure service in this case.

If you want to use Custom Vision Azure service you will need to use another Nuget package: Microsoft.Azure.CognitiveServices.Vision.CustomVision.Predition (or Training).

This could help some people.

**Comment by harrybanda** [comment]
Any solution for this problem?

**Comment by harrybanda** [comment]
The solution that worked for me:
1. Open your terminal and go to Import folder
2. paste this `dotnet add package Microsoft.Azure.CognitiveServices.Vision.CustomVision.Training --version 2.0.0`
this will update the CustomVision package.
3. Open Program.cs and replace this line `TrainingApi trainingApi = new TrainingApi() { ApiKey = trainingKey };` with this line `CustomVisionTrainingClient trainingApi = new CustomVisionTrainingClient(new Microsoft.Azure.CognitiveServices.Vision.CustomVision.Training.ApiKeyServiceClientCredentials(trainingKey)) {Endpoint = ENDPOINT};`
makesure to replace `ENDPOINT` with your yours from [customvision.ai](https://www.customvision.ai/)

**Comment by shonohs** [comment]
Closing this issue since the repository is deprecated. Thanks for the feedbacks.
