### ISSUE TITLE
Update API to 2.0

### ISSUE THREAD

**Issue by adamlepley** [microsoft/Cognitive-CustomVision-Windows#18]
The Custom Vision API has been updated to 2.0, but the code here and on Nuget is still 1.2.

**Comment by crnd** [comment]
Any progress with this? Seems like the [Object Detection guide](https://docs.microsoft.com/en-us/azure/cognitive-services/custom-vision-service/csharp-tutorial-od) uses the newer 2.0 API but as the NuGet package is still 1.2.0 it is not possible to follow the guide.

**Comment by adamlepley** [comment]
@crnd Seems that they moved to a different namespace for the .NET SDK for Custom Vision. See link below... 

[https://www.nuget.org/packages?q=Microsoft.Azure.CognitiveServices.Vision.CustomVision](https://www.nuget.org/packages?q=Microsoft.Azure.CognitiveServices.Vision.CustomVision)

**Comment by crnd** [comment]
@adamlepley Ah, thanks. Should've just read the guide properly...
