### ISSUE TITLE
Newly created project doesn't show up on custom vision portal

### ISSUE THREAD

**Issue by ac2707** [microsoft/Cognitive-CustomVision-Windows#22]
**
![image](https://user-images.githubusercontent.com/49182510/56263623-4448e400-6101-11e9-9307-3ab884ea09d2.png)
**
Created yet not visible -

![image](https://user-images.githubusercontent.com/49182510/56263640-588ce100-6101-11e9-82be-0b0c96803222.png)

Please advice.

**Comment by shonohs** [comment]
Support for Limited Trial projects has ended on 3/25/2019. Please follow this instruction to move your projects to Azure. 
https://docs.microsoft.com/en-us/azure/cognitive-services/custom-vision-service/move-your-project-to-azure

**Comment by wmustafaAwad** [comment]
I have the same problem. Found any solution to it?
The weirdest thing is: I found that the projects appeared from a friend's laptop, but not mine.

**Comment by shonohs** [comment]
Hello, this repository was deprecated in last October. Please contact Azure support team to fix the issue.
