### ISSUE TITLE
Could you provide the config parameters used by the CV trainer? 

### ISSUE THREAD

**Issue by jdsmith99** [microsoft/Cognitive-CustomVision-Windows#23]
I'd like to use the exported model w/OpenCV DNN. On edge devices, the OpenCV DNN is much faster and less processor intensive than the Tensorflow lib. The OpenCV DNN works with TensorFlow models from other trainers, and I *think* it'll work with the Azure Custom Vision models, but they need some tweaks. This repo: https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API has a converter tool but requires the config parameters used for training. The repo has a bunch of sample config files the converter script can use (https://github.com/tensorflow/models/tree/master/research/object_detection/samples/configs), but it's not clear which config settings the Custom Vision trainer uses. Could you provide the config file/settings in your github repo or as part of the ZIP file generated by the Export process? Or point to a config file in the OpenCV repo that you think will work? Thanks.

**Comment by shonohs** [comment]
Sorry for late response. Custom Vision service is not using TensorFlow in the backend. We don't have the config file.
