### ISSUE TITLE
Custome vision exported Onnx not working in windows ML.

### ISSUE THREAD

**Issue by SergioMasson** [microsoft/Cognitive-CustomVision-Windows#24]
I`m currently working on a project where we use the onnx model trained with costume vision on azure in order to perform offline object detection using the Windows.ML runtime. Since this Monday, our models exported from costume vision do not run in WindowsML. When bind method is called "winrt::Windows::AI::MachineLearning::LearningModelBinding" with a winrt::Windows::AI::MachineLearning::ImageFeatureValue created from the SoftwareBitmap of the camera. The bind method returns an exception with the following message: "Model variable data expects Float16[-1, 3, 416, 416]". This happens with all onnx models generated after Monday. Models generated before that work fine. Have Custom Vision changed the onnx  format that it generates?

**Comment by shonohs** [comment]
Hello,

Sorry for causing the trouble. We have a fix and we are now working on deployment. 

To work around the issue with the exported onnx files, please remove the following metadata from the model.
"Image.ColorSpaceGamma"

For the detail of the ONNX metadata, please see this document:
https://github.com/onnx/onnx/blob/master/docs/MetadataProps.md

**Comment by shonohs** [comment]
This fix has been deployed to all datacenters.
