### ISSUE TITLE
KEYs

### ISSUE THREAD

**Issue by PyWizNikhil** [microsoft/Cognitive-CustomVision-Windows#4]
Where can i get the training and prediction key

**Comment by chsienki** [comment]
Visit https://customvision.ai and sign up for an account.
Create a project (you can delete it afterwards) and open it. 
Click on the 'gear' icon at the top right hand side, which will list your keys.

**Note**: keys are per-user, not per-project, but currently the only way to see them on the website is in the context of an existing project.
