### ISSUE TITLE
How do I get the project id without using training module?

### ISSUE THREAD

**Issue by arafattehsin** [microsoft/Cognitive-CustomVision-Windows#6]
Hi

I have created the project online on customvision.ai and trained there as well.

I am not sure how can I get the project ID without creating the project from codebehind. Please let me know.

I'm only using the Predictions API, not the training one.

Thanks

**Comment by overbrimming** [comment]
I think what you're asking here is how to get the ProjectId for a project you created manually without using the Training API, ie from the user interface. From any page within a project on the custom vision site, the url is of the format: 
`https://customvision.ai/projects/{projectid}#/{page}.`

![image](https://user-images.githubusercontent.com/8257963/27058365-b43539b0-4f85-11e7-96a0-58a4bc1a9223.png)

If you are trying to use the Predictions API, you may find it helpful to go to the "Performance" tab and click on "Prediction URL". A sidebar will pop up with the prediction url for your iteration (including the projectId and various keys.

Btw, if you wanted to get a list of all your projects and their ids programmatically you would use the Training API's "Get Projects" operation: https://southcentralus.dev.cognitive.microsoft.com/docs/services/d9a10a4a5f8549599f1ecafc435119fa/operations/58d5835bc8cb231380095be9

**Comment by arafattehsin** [comment]
Yes I managed to do using the Training APIs. Thanks!
