### ISSUE TITLE
Issue in Predicting Images

### ISSUE THREAD

**Issue by arafattehsin** [microsoft/Cognitive-CustomVision-Windows#7]
Hi

I'm having an issue in predicting the images;

![issue](https://user-images.githubusercontent.com/16351038/27025905-bcc404f6-4f64-11e7-8630-f3b70df0e824.PNG)
![issue-2](https://user-images.githubusercontent.com/16351038/27025903-bc6fbdb0-4f64-11e7-8706-eaae6f11d0fa.PNG)

Please let me know how can I resolve them?

Thanks
Arafat

**Comment by Mimetis** [comment]
Exact same issue here.

Edit : Eventually, I found the issue. The Iteration must be explicitely declared :
```
var result = endpoint.PredictImage(towerProject.Id, testImage, new Guid("6c651131-c113-4ecb-b4ae-c852cec3b60d"));

```
This code works for me

**Comment by arafattehsin** [comment]
Hi @Mimetis, yes, I figured out later and not only this. The other way to achieve is to set the Custom Vision project as Default by choosing this;

![image](https://user-images.githubusercontent.com/16351038/27080602-59ae2086-5045-11e7-956a-7b8e384dc15c.png)

**Comment by Mimetis** [comment]
You're Right !! thx for the tips :)

**Comment by chsienki** [comment]
Yes, you have to have already set a default iteration if you don't provide an explicit iteration ID. You can see an example of how to set a default iteration programatically in the sample code: 

https://github.com/Microsoft/Cognitive-CustomVision-Windows/blob/master/Samples/CustomVision.Sample/Program.cs#L95
