### ISSUE TITLE
Add support for .NET Standard 2.0

### ISSUE THREAD

**Issue by CarlosSardo** [microsoft/Cognitive-CustomVision-Windows#9]
Hi,
Any plans to add support for [.NET Standard 2.0](https://github.com/dotnet/standard/blob/master/docs/versions/netstandard2.0.md) ?
Thanks!

**Comment by colombod** [comment]
Can the api generator target the .net standard instead of the desktop version??

**Comment by shonohs** [comment]
This repository is deprecated
